title: 下栗応援サークル
description: 下栗の里 (長野県飯田市) で農作業や交流活動を行っています。
permalink: 'posts/:year/:month/:day/:title'

# Author Settings
author: 下栗応援サークル
author-img: village_shimoguri.jpg
about-author: 　下栗の里は、南信州の秘境・遠山郷にある集落です。<br>　大自然に囲まれて農作業やイベントを楽しみながら、日本の未来や人生の未来を考えましょう！
social-facebook: shimoguri.ml
social-instagram: shimoguri.ml
social-github: shimoguri-supporters

# Disqus
discus-identifier: shimoguri

# Tracker
analytics: UA-23493957-5

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

timezone: Asia/Tokyo
